### ISSUE TITLE
Maximizing the area looses the connection

### ISSUE THREAD

**Issue by vilemduha** [jayanam/bl_ui_widgets#8]
Simply hitting ctrl+space to maximize area throws error and causes the sampel widget operator to hang:
I think the library should store the link to areas differently  (like indices or something), and should actively find a new area if it looses the original one, or end itself.

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\vilem\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\bl_ui_widgets-master\bl_ui_draw_op.py", line 60, in modal
    def modal(self, context, event):
  File "C:\Users\vilem\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\bl_ui_widgets-master\bl_ui_draw_op.py", line 52, in handle_widget_events

  File "C:\Users\vilem\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\bl_ui_widgets-master\bl_ui_widget.py", line 93, in handle_event
    inrect = self.is_in_rect(x, y)
  File "C:\Users\vilem\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\bl_ui_widgets-master\bl_ui_widget.py", line 119, in is_in_rect
    area_height = self.get_area_height()
  File "C:\Users\vilem\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\bl_ui_widgets-master\bl_ui_widget.py", line 116, in get_area_height
    return self.context.area.height
AttributeError: 'NoneType' object has no attribute 'height'

**Comment by jayanam** [comment]
Yes, ATM there is just the current area taken into account, have to
address this.

**Comment by vilemduha** [comment]
I'd like to help with this - I wrote you an email yesterday but not sure If I had youre email correctly.
